%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-pcl-conversions
Version:        2.5.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS pcl_conversions package

License:        BSD
URL:            http://wiki.ros.org/pcl_conversions
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       pcl
Requires:       pcl-devel
Requires:       ros-iron-message-filters
Requires:       ros-iron-pcl-msgs
Requires:       ros-iron-rclcpp
Requires:       ros-iron-sensor-msgs
Requires:       ros-iron-std-msgs
Requires:       ros-iron-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-message-filters
BuildRequires:  ros-iron-pcl-msgs
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-sensor-msgs
BuildRequires:  ros-iron-std-msgs
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-iron-ament-cmake-gtest
%endif

%description
Provides conversions from PCL data types and ROS message types

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Thu Jun 06 2024 Paul Bovbel <paul@bovbel.com> - 2.5.4-1
- Autogenerated by Bloom

* Wed Jun 05 2024 Paul Bovbel <paul@bovbel.com> - 2.5.3-1
- Autogenerated by Bloom

* Wed May 29 2024 Paul Bovbel <paul@bovbel.com> - 2.5.2-1
- Autogenerated by Bloom

* Thu Apr 04 2024 Paul Bovbel <paul@bovbel.com> - 2.5.1-1
- Autogenerated by Bloom

* Thu Apr 20 2023 Paul Bovbel <paul@bovbel.com> - 2.4.0-5
- Autogenerated by Bloom

* Tue Mar 21 2023 Paul Bovbel <paul@bovbel.com> - 2.4.0-4
- Autogenerated by Bloom

